version: "3.9"

services:
  server:
    image: aemdesign/java-buildpack:jdk11
    command: /bin/bash -i -l /automation-test.sh https://github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}.git ${GITHUB_REF_NAME} || exit 1
    working_dir: /
    volumes:
      - ./automation-test.sh:/automation-test.sh
      - ./scripts/profile.sh:/build/.profile
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=server
    networks:
      default:
        aliases:
          - server

  cypress:
    image: cypress/included:9.5.0
    working_dir: /source
    entrypoint: ""
    volumes:
      - ./:/source
    command: /bin/bash /source/scripts/wait-for-it.sh server:8080 -- cypress run --config baseUrl=http://server:8080
    networks:
      - default

  # docker-stop-server:
  #   image: docker:dind
  #   working_dir: /source
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: docker stop template-electron-vuex-vuetify-server-1
  #   depends_on:
  #     cypress:
  #       condition: service_completed_successfully

networks:
  default:
