version: "3.9"

services:

  # star server
  server:
    image: aemdesign/java-buildpack:jdk11
    command: /bin/bash -l /build/source/scripts/automation-test.sh
    working_dir: /build/source
    volumes:
      - ./:/build/source
    environment:
      - NODE_ENV=dev
      - PORT=8080
      - HOST=server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8080"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 2s
    networks:
      default:
        aliases:
          - server

  # run tests
  cypress:
    image: cypress/included:9.5.0
    working_dir: /source
    volumes:
      - ./:/source
    command: run --config baseUrl=http://server:8080
    depends_on:
      server:
        condition: service_healthy
    networks:
      - default

  # force server exit if cypress has finished
  docker-stop-on-cypress:
    image: docker:dind
    working_dir: /source
    volumes:
      - ./:/source
      - /var/run/docker.sock:/var/run/docker.sock
    command: docker compose down
    depends_on:
      cypress:
        condition: service_completed_successfully

  # force server exit if cypress has finished
  docker-stop-on-server:
    image: docker:dind
    working_dir: /source
    volumes:
      - ./:/source
      - /var/run/docker.sock:/var/run/docker.sock
    command: docker compose down
    depends_on:
      service:
        condition: service_completed_successfully

networks:
  default:
