version: "3.9"

services:
  server:
    image: circleci/node:latest-browsers
    hostname: server
    command: bash -c "npm install && npm run preview:ci"
    working_dir: /source
    volumes:
      - ./:/source
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=host.docker.internal
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8080"]
      interval: 10s
      timeout: 5s
      retries: 300
      start_period: 10s
    networks:
      - default

  cypress:
    image: cypress/included:9.5.0
    working_dir: /source
    volumes:
      - ./:/source
    command: run --config baseUrl=http://host.docker.internal:8080
    depends_on:
      server:
        condition: service_healthy

  # docker-stop-server:
  #   image: docker:dind
  #   working_dir: /source
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: docker stop template-electron-vuex-vuetify-server-1
  #   depends_on:
  #     cypress:
  #       condition: service_completed_successfully
