version: "3.9"

services:
  server:
    image: aemdesign/java-buildpack:jdk11-ubuntu
    command: bash -l /source/automation-test.sh "https://github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY}.git" "${GITHUB_REF_NAME}"
    working_dir: /source
    volumes:
      - ./:/source
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8080"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 2s
    networks:
      default:
        aliases:
          - server

  cypress:
    image: cypress/included:9.5.0
    working_dir: /source
    volumes:
      - ./:/source
    command: run --config baseUrl=http://server:8080
    depends_on:
      server:
        condition: service_healthy
    networks:
      - default
  # docker-stop-server:
  #   image: docker:dind
  #   working_dir: /source
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: docker stop template-electron-vuex-vuetify-server-1
  #   depends_on:
  #     cypress:
  #       condition: service_completed_successfully

networks:
  default:
