name: Unit Test

on:
  push:
    branches:
      - "*"

jobs:
  test-functional:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14.13.1]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            friendlyName: Functional Test - Ubuntu

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run Cypress using Docker
        run: |
            docker compose up --abort-on-container-exit --quiet-pull --renew-anon-volumes --exit-code-from server
